概率基础学习中，multinomial包中Multinomial类的使用方法

该类接收四个参数：multinomial.Multinomial(total_count=1, probs=None, logits=None, validate_args=None)
- total_count 指单次抽样中样本的个数，int型
- probs 指各个事件发生的概率，tensor型，可传入概率也可以传入频数（我理解的就是事件共发生的次数），可以通过props属性查看概率分布

In [5]:
import torch
from torch.distributions import multinomial
fair_probs = torch.ones(6) / 6 #传入概率
fair_probs_c = torch.ones(6) #频数
x = multinomial.Multinomial(1, fair_probs).probs
y = multinomial.Multinomial(1, fair_probs_c).probs
print(x)
print(y)

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])
tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])


- logits 指各个事件概率的自然对数 tensor型，同样可以传概率的自然对数和频数的自然对数
- valid_args 指是否检查参数的合法性，默认True，在手动设置为False后，也会检查参数的合法性
**注意：probs和logits不能同时传入，也不能都不传入，否则会报错**

sample()是Mlutinomial类的一个抽象函数，唯一传参为(sample_shape=torch.Size())，用来指定抽样的次数，默认抽样一次，输出一个形状为(len(probs))的张量，否则输出((sample_shape, len(probs)))
**samele((a, b))的sample_shape参数的意思是抽样a组，每一组抽样b次，如下代码中给sample传入了(5, 3)大小的抽样形状，输出为(5， 3， 6)的一个三维张量**

In [6]:
fair_probs = torch.ones(6) / 6 #传入概率
x = multinomial.Multinomial(1, fair_probs).sample((5, 3))
print(x)

tensor([[[0., 0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1.]],

        [[0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0.]],

        [[0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 1., 0., 0., 0.]],

        [[0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0.]]])


通过命令查看包中的函数和类的官方内容：

In [8]:
print(dir(torch.multinomial))

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__text_signature__']


查看特定函数和类的用法：

In [9]:
help(multinomial.Multinomial)

Help on class Multinomial in module torch.distributions.multinomial:

class Multinomial(torch.distributions.distribution.Distribution)
 |  Multinomial(total_count=1, probs=None, logits=None, validate_args=None)
 |  
 |  Creates a Multinomial distribution parameterized by :attr:`total_count` and
 |  either :attr:`probs` or :attr:`logits` (but not both). The innermost dimension of
 |  :attr:`probs` indexes over categories. All other dimensions index over batches.
 |  
 |  Note that :attr:`total_count` need not be specified if only :meth:`log_prob` is
 |  called (see example below)
 |  
 |  .. note:: The `probs` argument must be non-negative, finite and have a non-zero sum,
 |            and it will be normalized to sum to 1 along the last dimension. :attr:`probs`
 |            will return this normalized value.
 |            The `logits` argument will be interpreted as unnormalized log probabilities
 |            and can therefore be any real number. It will likewise be normalized so tha