# transforms.ToTensor 的使用
将PIL的图像格式或则ndarray转换为张量，如果PIL或ndarray满足条件，会直执行除255，让数值在0-1区间

In [1]:
import torchvision
import torch
from torchvision import transforms

help(transforms.ToTensor)

Help on class ToTensor in module torchvision.transforms.transforms:

class ToTensor(builtins.object)
 |  ToTensor() -> None
 |  
 |  Convert a PIL Image or ndarray to tensor and scale the values accordingly.
 |  
 |  This transform does not support torchscript.
 |  
 |  Converts a PIL Image or numpy.ndarray (H x W x C) in the range
 |  [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]
 |  if the PIL Image belongs to one of the modes (L, LA, P, I, F, RGB, YCbCr, RGBA, CMYK, 1)
 |  or if the numpy.ndarray has dtype = np.uint8
 |  
 |  In the other cases, tensors are returned without scaling.
 |  
 |  .. note::
 |      Because the input image is scaled to [0.0, 1.0], this transformation should not be used when
 |      transforming target image masks. See the `references`_ for implementing the transforms for image masks.
 |  
 |  .. _references: https://github.com/pytorch/vision/tree/main/references/segmentation
 |  
 |  Methods defined here:
 |  
 |  __call__(se

# 下载数据集，使用torchvision.datasets
提供了多种数据集，下载数据集传参一般如下：
- root：数据集根目录
- train：是否作为训练集
- transform： 应用的转换操作
- download： 是否自动下载，True时执行自动下载，如果目录下已有不会重复下载，False时，如果目录下不存在数据集，则跑出异常

In [2]:
help(torchvision.datasets)

Help on package torchvision.datasets in torchvision:

NAME
    torchvision.datasets

PACKAGE CONTENTS
    _optical_flow
    _stereo_matching
    caltech
    celeba
    cifar
    cityscapes
    clevr
    coco
    country211
    dtd
    eurosat
    fakedata
    fer2013
    fgvc_aircraft
    flickr
    flowers102
    folder
    food101
    gtsrb
    hmdb51
    imagenet
    inaturalist
    kinetics
    kitti
    lfw
    lsun
    mnist
    moving_mnist
    omniglot
    oxford_iiit_pet
    pcam
    phototour
    places365
    rendered_sst2
    samplers (package)
    sbd
    sbu
    semeion
    stanford_cars
    stl10
    sun397
    svhn
    ucf101
    usps
    utils
    video_utils
    vision
    voc
    widerface

CLASSES
    torch.utils.data.dataset.Dataset(typing.Generic)
        torchvision.datasets.vision.VisionDataset
            torchvision.datasets.caltech.Caltech101
            torchvision.datasets.caltech.Caltech256
            torchvision.datasets.celeba.CelebA
            torchvi

# 高级索引（花式索引）
允许使用一个索引数组或者列表，同时选择张量中的多个元素

In [3]:
import torch

y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])

result = y_hat[[0, 1], y] 
# 使用列表[0, 1]和y作为索引，输出的是y_hat[0][0]和y_hat[1][2]
print(result)

tensor([0.1000, 0.5000])


In [4]:
help(torch.argmax)

Help on built-in function argmax in module torch:

argmax(...)
    argmax(input) -> LongTensor
    
    Returns the indices of the maximum value of all elements in the :attr:`input` tensor.
    
    This is the second value returned by :meth:`torch.max`. See its
    documentation for the exact semantics of this method.
    
    .. note:: If there are multiple maximal values then the indices of the first maximal value are returned.
    
    Args:
        input (Tensor): the input tensor.
    
    Example::
    
        >>> a = torch.randn(4, 4)
        >>> a
        tensor([[ 1.3398,  0.2663, -0.2686,  0.2450],
                [-0.7401, -0.8805, -0.3402, -1.1936],
                [ 0.4907, -1.3948, -1.0691, -0.3132],
                [-1.6092,  0.5419, -0.2993,  0.3195]])
        >>> torch.argmax(a)
        tensor(0)
    
    .. function:: argmax(input, dim, keepdim=False) -> LongTensor
       :noindex:
    
    Returns the indices of the maximum values of a tensor across a dimension.
  

In [5]:
help(isinstance)

Help on built-in function isinstance in module builtins:

isinstance(obj, class_or_tuple, /)
    Return whether an object is an instance of a class or of a subclass thereof.
    
    A tuple, as in ``isinstance(x, (A, B, ...))``, may be given as the target to
    check against. This is equivalent to ``isinstance(x, A) or isinstance(x, B)
    or ...`` etc.


# 创建类Accumulator

In [30]:
class Accumulator:
    def __init__(self, n):
        self.data = [0.0] * n
    
    def add(self, *args):
            self.data = [a + float(b) for a, b in zip(self.data, args)] # 当这个函数被调用时，是对data属性进行重新赋值

acc = Accumulator(2) # 实例化的时候，立刻调用初始化方法，手动传参n，就可以直接访问类的属性data， 打印出实例acc.data
# acc.data[0] = 1.0
acc.add(23.0, 256)
print(acc.data)


(23.0, 256)
(23.0, 256)
[23.0, 256.0]


In [34]:
z = zip([1, 2, 3], [4, 5, 6])
print(next(z))

(1, 4)


In [31]:
class Rectangle:
    # 定义初始化成员方法，也称为构造函数，在实例化Rectangle类时被调用，用于初始化实例对象的属性
    # 该构造函数接收两个传参：width和height，在实例化时传入这两个参数的值，该方法可以将传参值赋值给实例对象
    def __init__(self, width, height): 
        self.width = width
        self.height = height
    
    # 定义area成员方法，调用该方法返回面积，属性width和height的乘积
    def area(self):
        return self.width * self.height

    def perimeter(self):
        return 2 * (self.width + self.height)

    def is_square(self):
        return self.width == self.height

aa = Rectangle(5, 10)
print(aa.width, aa.height)

print(aa.area())

5 10
50


In [21]:
# 自己定义一个类
class cat:
    def __init__(self, color):
        self.color = color
    
    def category(self, fur_color):
        if fur_color == 'yellow':
            print('ginger cat')
        else:
            print('dog')
            

kitty1 = cat('yellow')
print(kitty1.color)
kitty1.category('black')

yellow
dog


In [37]:
a = torch.tensor([50])
print(torch.exp(a))

tensor([5.1847e+21])


# nn.init.normal_()
初始化张量的方法，对参数中的张量直接初始化赋值，不返回新的张量，参数如下：
- tensor：需要初始化的张量
- mean：默认0.0
- std：默认1.0

In [38]:
help(torch.nn.init.normal_)

Help on function normal_ in module torch.nn.init:

normal_(tensor: torch.Tensor, mean: float = 0.0, std: float = 1.0) -> torch.Tensor
    Fills the input Tensor with values drawn from the normal
    distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`.
    
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
    
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.normal_(w)


# nn.CrossEntropyLoss 封装好的交叉熵损失，类

In [40]:
help(torch.nn.CrossEntropyLoss)

Help on class CrossEntropyLoss in module torch.nn.modules.loss:

class CrossEntropyLoss(_WeightedLoss)
 |  CrossEntropyLoss(weight: Union[torch.Tensor, NoneType] = None, size_average=None, ignore_index: int = -100, reduce=None, reduction: str = 'mean', label_smoothing: float = 0.0) -> None
 |  
 |  This criterion computes the cross entropy loss between input logits
 |  and target.
 |  
 |  It is useful when training a classification problem with `C` classes.
 |  If provided, the optional argument :attr:`weight` should be a 1D `Tensor`
 |  assigning weight to each of the classes.
 |  This is particularly useful when you have an unbalanced training set.
 |  
 |  The `input` is expected to contain the unnormalized logits for each class (which do `not` need
 |  to be positive or sum to 1, in general).
 |  `input` has to be a Tensor of size :math:`(C)` for unbatched input,
 |  :math:`(minibatch, C)` or :math:`(minibatch, C, d_1, d_2, ..., d_K)` with :math:`K \geq 1` for the
 |  `K`-dimensio